# Generated by Django 5.2 on 2025-09-03 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='predict_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Predict',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('percentage', models.PositiveIntegerField(default=0)),
                ('result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predicts', to='model.dataclass')),
            ],
        ),
    ]
