# Generated by Django 5.0.6 on 2024-11-29 10:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilangan vaqti')),
                ('title', models.CharField(max_length=250, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif/Izoh')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DataClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilangan vaqti')),
                ('title', models.CharField(max_length=250, verbose_name='Nomi')),
                ('label', models.CharField(max_length=250, verbose_name='Label')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsif/Izoh')),
                ('data_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classes', to='model.datamodel', verbose_name='Model')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
