# Generated by Django 5.0.6 on 2024-11-29 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataclass',
            name='label',
            field=models.CharField(max_length=250, unique=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='dataclass',
            name='title',
            field=models.CharField(max_length=250, unique=True, verbose_name='Nomi'),
        ),
    ]
