# Generated by Django 5.2 on 2025-09-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataclass',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif/Izoh'),
        ),
        migrations.AddField(
            model_name='dataclass',
            name='description_ru',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif/Izoh'),
        ),
        migrations.AddField(
            model_name='dataclass',
            name='description_uz',
            field=models.TextField(blank=True, null=True, verbose_name='Tavsif/Izoh'),
        ),
        migrations.AddField(
            model_name='dataclass',
            name='title_en',
            field=models.CharField(max_length=250, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='dataclass',
            name='title_ru',
            field=models.CharField(max_length=250, null=True, verbose_name='Nomi'),
        ),
        migrations.AddField(
            model_name='dataclass',
            name='title_uz',
            field=models.CharField(max_length=250, null=True, verbose_name='Nomi'),
        ),
    ]
