# Generated by Django 5.2 on 2025-09-03 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_dataclass_description_en_dataclass_description_ru_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataclass',
            options={'verbose_name': 'Kasallik klassi', 'verbose_name_plural': 'Kasallik klasslari'},
        ),
        migrations.AlterModelOptions(
            name='datamodel',
            options={'verbose_name': 'Model', 'verbose_name_plural': 'Modellar'},
        ),
    ]
