# Generated by Django 5.1.3 on 2024-12-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0002_alter_dataclass_label_alter_dataclass_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataclass',
            name='title',
            field=models.CharField(max_length=250, verbose_name='Nomi'),
        ),
    ]
