# Generated by Django 5.1.3 on 2024-12-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_alter_dataclass_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataclass',
            name='label',
            field=models.CharField(max_length=250, verbose_name='Label'),
        ),
        migrations.AlterUniqueTogether(
            name='dataclass',
            unique_together={('data_model', 'label')},
        ),
    ]
