# Generated by Django 5.2 on 2025-10-25 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0003_alter_dataclass_options_alter_datamodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dataclass',
            options={'verbose_name': 'Model klassi', 'verbose_name_plural': 'Model klasslari'},
        ),
    ]
