# Generated by Django 5.2 on 2025-11-17 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_diseaselevel_description_diseaselevel_index_and_more'),
        ('model', '0004_alter_dataclass_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodel',
            name='disease_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='data_models', to='base.diseasetype', verbose_name='Kasallik turi'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='datamodel',
            name='description',
            field=models.TextField(default=1, verbose_name='Tavsif/Izoh'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='datamodel',
            unique_together={('disease_type', 'code')},
        ),
    ]
