# Generated by Django 5.1.3 on 2024-12-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0004_alter_dataclass_label_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dataclass',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='dataclass',
            name='index',
            field=models.PositiveIntegerField(default=0, verbose_name='Index'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='dataclass',
            name='label',
        ),
    ]
