# Generated by Django 5.1.3 on 2024-12-09 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0005_alter_dataclass_unique_together_dataclass_index_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dataclass',
            unique_together={('data_model', 'index')},
        ),
    ]
