# Generated by Django 5.2 on 2025-07-14 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('model', '0006_alter_dataclass_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodel',
            name='code',
            field=models.CharField(default='cnn', max_length=10),
            preserve_default=False,
        ),
    ]
