# Generated by Django 5.0.6 on 2024-07-03 06:49

import base.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiseaseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilangan vaqti')),
                ('title', models.CharField(max_length=150, verbose_name='Nomi')),
                ('title_uz', models.CharField(max_length=150, null=True, verbose_name='Nomi')),
                ('title_ru', models.CharField(max_length=150, null=True, verbose_name='Nomi')),
                ('title_en', models.CharField(max_length=150, null=True, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Kasallik turi',
                'verbose_name_plural': 'Kasallik Turlari',
                'db_table': 'disease_types',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='TomatoType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilangan vaqti')),
                ('title', models.CharField(max_length=150, verbose_name='Nomi')),
                ('title_uz', models.CharField(max_length=150, null=True, verbose_name='Nomi')),
                ('title_ru', models.CharField(max_length=150, null=True, verbose_name='Nomi')),
                ('title_en', models.CharField(max_length=150, null=True, verbose_name='Nomi')),
            ],
            options={
                'verbose_name': 'Pomidor turi',
                'verbose_name_plural': 'Pomidor Turlari',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='DiseaseLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilangan vaqti')),
                ('title', models.CharField(max_length=150, verbose_name='Nomi')),
                ('title_uz', models.CharField(max_length=150, null=True, verbose_name='Nomi')),
                ('title_ru', models.CharField(max_length=150, null=True, verbose_name='Nomi')),
                ('title_en', models.CharField(max_length=150, null=True, verbose_name='Nomi')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_levels', to='base.diseasetype')),
            ],
            options={
                'verbose_name': 'Kasallik darajasi',
                'verbose_name_plural': 'Kasallik Darajalari',
                'db_table': 'disease_levels',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='ImageData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqti')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Oxirgi yangilangan vaqti')),
                ('source', models.ImageField(upload_to=base.models.image_data_path)),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='base.diseaselevel')),
            ],
            options={
                'verbose_name': 'Rasm',
                'verbose_name_plural': 'Rasmlar',
                'db_table': 'dataset_images',
                'ordering': ['-created_time'],
            },
        ),
        migrations.AddField(
            model_name='diseasetype',
            name='tomato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disease_types', to='base.tomatotype'),
        ),
    ]
