# Generated by Django 5.2 on 2025-10-23 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TomatoType',
            new_name='PlantType',
        ),
        migrations.AlterModelOptions(
            name='planttype',
            options={'ordering': ['-created_time'], 'verbose_name': "O'simlik turi", 'verbose_name_plural': "O'simlik turlari"},
        ),
        migrations.RenameField(
            model_name='diseasetype',
            old_name='tomato',
            new_name='plant',
        ),
    ]
