# Generated by Django 5.2 on 2025-11-17 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_tomatotype_planttype_alter_planttype_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='diseaselevel',
            name='description',
            field=models.TextField(default=1, verbose_name='Tavsif/Izoh'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseaselevel',
            name='index',
            field=models.PositiveIntegerField(default=1, verbose_name='Index'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diseasetype',
            name='description',
            field=models.TextField(default=1, verbose_name='Tavsif/Izoh'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='planttype',
            name='description',
            field=models.TextField(default=1, verbose_name='Tavsif/Izoh'),
            preserve_default=False,
        ),
    ]
